#!/usr/bin/env python3
"""Emit the descriptor-family graph, from the catalogue itself.  2026-09-01

Two views of the same 117 descriptors: the six **families** are what produces them (one pass of
one command each), and the invariance **classes** are what they mean. The figure exists because
the two do not line up -- the topology family is mostly compositional, and the geometric
descriptors that describe the docking sit in `placement`, which no shipped block reads.

    python scripts/gen_family_graph.py                 # docs/_static/descriptor_families.{dot,svg,pdf}
    python scripts/gen_family_graph.py --check         # exit 1 if the .dot would change
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path

from tcren.recognition import FAMILIES, INVARIANCE, descriptors

OUT_DIR = Path(__file__).resolve().parents[1] / "docs" / "_static"
DOT = OUT_DIR / "descriptor_families.dot"

#: Okabe-Ito, so the figure survives greyscale and colour blindness.
CLASS_COLOUR = {
    "geometric": "#0072B2",       # blue      -- the docking
    "topological": "#D55E00",     # vermillion-- the interface surface
    "compositional": "#009E73",   # green     -- counts over the labelled contact set
    "energetic": "#CC79A7",       # rose      -- the potentials
    "categorical": "#999999",     # grey      -- MHC class I or II
}
CLASS_GLOSS = {
    "geometric": "preserved by isometry\\na length, area, angle or cosine",
    "topological": "preserved by homeomorphism\\nBetti numbers, Euler characteristic",
    "compositional": "a count over the labelled\\ncontact set, or a share of one",
    "energetic": "a statistical-potential\\nor Potts energy",
    "categorical": "which class of MHC\\npresents the peptide",
}
FAMILY_GLOSS = {
    "placement": "where the receptor sits",
    "interface": "how much contact, of what kind",
    "topology": "the footprint",
    "energetics": "referenced interface energy",
    "potts": "energy against the partition function",
    "kinetics": "the interface as springs",
}


def _plural(n: int) -> str:
    return f"{n} descriptor" if n == 1 else f"{n} descriptors"


def render() -> str:
    counts = {f: Counter(INVARIANCE[d] for d in descriptors(f)) for f in FAMILIES}
    totals = Counter()
    for c in counts.values():
        totals += c

    L = [
        "// GENERATED by scripts/gen_family_graph.py -- do not edit.",
        "digraph descriptor_families {",
        '  rankdir=LR; bgcolor="transparent"; splines=true; nodesep=0.18; ranksep=1.1;',
        '  node [shape=box, style="rounded,filled", fontname="Helvetica", fontsize=10,',
        '        color="#4D4D4D", penwidth=0.8];',
        '  edge [fontname="Helvetica", fontsize=8, color="#4D4D4D", arrowsize=0.6];',
        "",
        "  // what produces them: one pass of one command per family",
        '  subgraph cluster_family {',
        '    label="families\\nwhat computes them"; fontname="Helvetica-Bold"; fontsize=11;',
        '    color="#BFBFBF"; style=rounded;',
    ]
    for f in FAMILIES:
        n = len(descriptors(f))
        L.append(f'    "{f}" [fillcolor="#F2F2F2", '
                 f'label="{f}\\n{_plural(n)}\\n{FAMILY_GLOSS[f]}"];')
    L += ["  }", "",
          "  // what they mean: the invariance the quantity is defined up to",
          '  subgraph cluster_class {',
          '    label="invariance\\nwhat they mean"; fontname="Helvetica-Bold"; fontsize=11;',
          '    color="#BFBFBF"; style=rounded;']
    for cls, colour in CLASS_COLOUR.items():
        L.append(f'    "{cls}" [fillcolor="{colour}", fontcolor="white", '
                 f'label="{cls}\\n{_plural(totals[cls])}\\n{CLASS_GLOSS[cls]}"];')
    L += ["  }", ""]

    for f in FAMILIES:
        for cls, n in sorted(counts[f].items(), key=lambda kv: -kv[1]):
            width = 0.6 + 2.6 * n / 31.0
            L.append(f'  "{f}" -> "{cls}" [label="{n}", penwidth={width:.2f}, '
                     f'color="{CLASS_COLOUR[cls]}"];')
    L += ["}", ""]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if not DOT.exists() or DOT.read_text() != text:
            print(f"{DOT} is out of date; re-run scripts/gen_family_graph.py", file=sys.stderr)
            return 1
        print(f"{DOT} is current")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DOT.write_text(text)
    print(f"wrote {DOT}")
    if shutil.which("dot"):
        for fmt in ("svg", "pdf"):
            target = DOT.with_suffix(f".{fmt}")
            subprocess.run(["dot", f"-T{fmt}", str(DOT), "-o", str(target)], check=True)
            print(f"wrote {target}")
    else:
        print("graphviz `dot` not on PATH; wrote the .dot only", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
