#!/usr/bin/env python3
"""Emit the full descriptor table for the docs, from the catalogue itself.  2026-09-01

The table is generated so it cannot drift: a descriptor added to ``recognition.DESCRIPTORS``
without a ``DETAIL`` entry fails the catalogue's own completeness test, and re-running this brings
the docs into line. ``tests/unit/test_descriptor_table.py`` asserts the committed file matches.

    python scripts/gen_descriptor_table.py            # rewrite docs/descriptor_table.rst
    python scripts/gen_descriptor_table.py --check    # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tcren.recognition import DESCRIPTORS, DETAIL, FAMILIES, INVARIANCE, descriptors

OUT = Path(__file__).resolve().parents[1] / "docs" / "descriptor_table.rst"

FAMILY_BLURB = {
    "placement": "Where the receptor sits on the groove and how it leans. Every column is a "
                 "length, an angle or a direction cosine, so the family is geometric throughout.",
    "interface": "How much contact there is and of what chemical kind. Two continuous "
                 "quantities -- buried surface and clash depth -- and counts for the rest.",
    "topology": "The footprint: its connectivity, its composition over labelled cells, and how "
                "the receptor's contacts spread along the peptide.",
    "energetics": "Statistical-potential interface sums and their poly-alanine references. "
                  "Lower is more favourable.",
    "potts": "The same interface read against the partition function of the coupled contact "
             "model rather than against a poly-alanine interface.",
    "kinetics": "The contact map as a network of breakable springs. No potential enters: these "
                "are geometry and multiplicity, which is why they carry evidence the energies "
                "cannot.",
}


def _rows(names: tuple[str, ...]) -> list[str]:
    out = []
    for name in names:
        units, definition = DETAIL[name]
        receptor = "yes" if DESCRIPTORS[name][1] else "**no**"
        out += [
            f"   * - ``{name}``",
            f"     - {INVARIANCE[name]}",
            f"     - {units}",
            f"     - {receptor}",
            f"     - {definition}",
        ]
    return out


def render() -> str:
    total = len(descriptors())
    lines = [
        ".. This file is GENERATED by scripts/gen_descriptor_table.py -- do not edit it.",
        "",
        "Every descriptor, with its units",
        "================================",
        "",
        f"All {total} descriptors ``tcren features --all`` emits, in catalogue order, with what "
        "each is",
        "invariant under and what it is measured in. The *receptor* column says whether the TCR "
        "enters the",
        "definition: a column marked **no** is computed from the peptide and its allele alone, so "
        "every",
        "structure of one epitope on one allele shares its value whatever the receptor, and it "
        "carries cohort",
        "identity rather than interface physics.",
        "",
        "Units are what a transform has to respect. A ``count`` is variance-stabilized by a square "
        "root, a",
        "``fraction`` by the arcsine -- the classical angular transformation -- and an unbounded "
        "continuous",
        "quantity by neither.",
        "",
    ]
    for family in FAMILIES:
        names = descriptors(family)
        if not names:
            continue
        title = f"{family} ({len(names)})"
        lines += [title, "-" * len(title), "", FAMILY_BLURB.get(family, ""), "",
                  ".. list-table::", "   :header-rows: 1", "   :widths: 18 14 10 8 50", "",
                  "   * - descriptor", "     - invariance", "     - units", "     - receptor",
                  "     - definition"]
        lines += _rows(names)
        lines += [""]

    from tcren.recognition import STATUS

    title = f"flagged descriptors ({len(STATUS)})"
    lines += [title, "-" * len(title), "",
              "Descriptors that need a second look before they are used, from "
              "``tcren.recognition.STATUS``.",
              "A name absent from this table has no known defect; presence is **not** a reason to "
              "drop the",
              "column, only to know what it is. ``suspicious`` means the quantity is not measuring "
              "what its",
              "family name suggests -- it reads the generator, or is fixed by an exact identity "
              "over other",
              "columns, or identifies the cohort rather than the complex. ``stalled`` means it is "
              "defined but",
              "does not move on the corpus.",
              "",
              ".. list-table::", "   :header-rows: 1", "   :widths: 20 12 68", "",
              "   * - descriptor", "     - flag", "     - why"]
    for name, (flag, why) in STATUS.items():
        lines += [f"   * - ``{name}``", f"     - {flag}", f"     - {why}"]
    lines += [""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the file would change")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date; re-run scripts/gen_descriptor_table.py", file=sys.stderr)
            return 1
        print(f"{OUT} is current")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
